version: '3.8'

services:
  php:
    container_name: php
    build:
      context: docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
