framework:
  http_client:
    scoped_clients:
      movie.client:
        base_uri: '%env(MOVIE_BASE_URI)%'
        headers:
          Accept: 'application/json'
          Authorization: 'Bearer %env(MOVIE_API_TOKEN)%'
        retry_failed:
          max_retries: 3
          delay: 500
          multiplier: 2
          max_delay: 3000
          jitter: 0.3

when@test:
  framework:
    http_client:
      scoped_clients:
        movie.client:
          base_uri: '%env(MOVIE_BASE_URI)%'
          headers:
            Accept: 'application/json'
            Authorization: 'Bearer %env(MOVIE_API_TOKEN)%'
          retry_failed:
            max_retries: 3
            delay: 500
            multiplier: 2
            max_delay: 3000
            jitter: 0.3
